#!/bin/sh

# 删除默认WiFi
uci -q delete wireless.@wifi-iface[0]
uci -q delete wireless.@wifi-iface[0]

# ===== 5G =====
uci add wireless wifi-iface
uci set wireless.@wifi-iface[-1].device='radio1'
uci set wireless.@wifi-iface[-1].mode='ap'
uci set wireless.@wifi-iface[-1].ssid='BAIN_5G'
uci set wireless.@wifi-iface[-1].encryption='sae-mixed'
uci set wireless.@wifi-iface[-1].key='13122996088'
uci set wireless.@wifi-iface[-1].network='lan'

uci set wireless.radio1.country='CN'
uci set wireless.radio1.channel='36'
uci set wireless.radio1.htmode='HE160'
uci set wireless.radio1.txpower='24'
uci set wireless.radio1.ampdu='1'
uci set wireless.radio1.wmm='1'
uci set wireless.radio1.txbf='1'
uci set wireless.radio1.mu_mimo='1'
uci set wireless.radio1.noscan='1'
uci set wireless.radio1.disabled='0'

# ===== 2.4G =====
uci add wireless wifi-iface
uci set wireless.@wifi-iface[-1].device='radio0'
uci set wireless.@wifi-iface[-1].mode='ap'
uci set wireless.@wifi-iface[-1].ssid='BAIN'
uci set wireless.@wifi-iface[-1].encryption='psk2+ccmp'  # 修复这里
uci set wireless.@wifi-iface[-1].key='13122996088'
uci set wireless.@wifi-iface[-1].network='lan'

uci set wireless.radio0.country='CN'
uci set wireless.radio0.channel='6'
uci set wireless.radio0.htmode='HT20'
uci set wireless.radio0.hwmode='11g'
uci set wireless.radio0.txpower='20'
uci set wireless.radio0.ampdu='0'
uci set wireless.radio0.wmm='1'
uci set wireless.radio0.disabled='0'

uci commit wireless
wifi reload

exit 0
